sudo: require
language: generic
services:
  - docker
before_install:
  - docker build -t surabhiojha12/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true surabhiojha12/react-test npm run test
after_success:
  - docker build -t surabhiojha12/multi-client ./client
  - docker build -t surabhiojha12/multi-nginx ./nginx
  - docker build -t surabhiojha12/multi-server ./server
  - docker build -t surabhiojha12/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push surabhiojha12/multi-client
  - docker push surabhiojha12/multi-nginx
  - docker push surabhiojha12/multi-server
  - docker push surabhiojha12/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-681696340465'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
